name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.asdf/**
            vendor/bundle
          key: ${{ runner.os }}-cache-${{ hashFiles('**/cache.key') }}
          restore-keys: |
            ${{ runner.os }}-cache-
      
      - name: Deploy to GitHub Pages
        uses: jeffreytse/jekyll-deploy-action@v0.6.0
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ''
          branch: 'gh-pages'
          jekyll_src: './'
          jekyll_cfg: '_config.yml'
          jekyll_baseurl: ''
          bundler_ver: '>=0'
          cname: ''